package hoavd.demo.laptopvn.common.constants;

public interface ResponseMessageConstants {
  //SYSTEM
  String ERROR = "MSG_ERROR";
  String ERR_SYSTEM = "MSG_ERROR_SYSTEM";
  String INFORMATION_INVALID = "MSG_INFORMATION_INVALID";
  String AUTHENTICATION_EXCEPTION = "MSG_AUTHENTICATION_EXCEPTION";

  //LOGIN
  String LOGIN_SUCCESS = "MSG_LOGIN_SUCCESS";
  String TOKEN_EXPIRED = "MSG_TOKEN_EXPIRED";
  String TOKEN_INVALID = "MSG_TOKEN_INVALID";
  String LOGIN_REFRESH_EXCEPTION = "MSG_LOGIN_REFRESH_EXCEPTION";

  //ADMIN
  String ADMIN_DOES_NOT_EXIST = "MSG_ADMIN_DOES_NOT_EXIST";
  String EMAIL_ALREADY_EXIST = "MSG_EMAIL_ALREADY_EXIST";
  String CREATE_ACC_ADMIN_SUCCESS = "MSG_CREATE_ACC_ADMIN_SUCCESS";
  String UPDATE_ACC_ADMIN_SUCCESS = "MSG_UPDATE_ACC_ADMIN_SUCCESS";
  String DELETE_ACC_ADMIN_SUCCESS = "MSG_DELETE_ACC_ADMIN_SUCCESS";

  //USER
  String USER_DOES_NOT_EXIST = "MSG_USER_DOES_NOT_EXIST";
  String CREATE_ACC_USER_SUCCESS = "MSG_CREATE_ACC_USER_SUCCESS";
  String UPDATE_ACC_USER_SUCCESS = "MSG_UPDATE_ACC_USER_SUCCESS";
  String DELETE_ACC_USER_SUCCESS = "MSG_DELETE_ACC_USER_SUCCESS";

  //CATEGORY
  String CATEGORY_NAME_ALREADY_EXIST = "MSG_CATEGORY_NAME_ALREADY_EXIST";
  String CATEGORY_DOES_NOT_EXIST = "MSG_CATEGORY_DOES_NOT_EXIST";
  String CREATE_CATEGORY_SUCCESS = "MSG_CREATE_CATEGORY_SUCCESS";
  String UPDATE_CATEGORY_SUCCESS = "MSG_UPDATE_CATEGORY_SUCCESS";
  String DELETE_CATEGORY_SUCCESS = "MSG_DELETE_CATEGORY_SUCCESS";
}
